basic_poll_app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

basic_poll_app/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

basic_poll_app/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

basic_poll_app/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('pub_date')
    context = {"latest_question_list" : latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/detail.html', {"question":question})

def results(request, question_id):
    response = "Result page: Question ID: %s" % question_id
    return HttpResponse(response)

def vote(request, question_id):
    return HttpResponse("Voting page: Question ID: %s" % question_id)

basic_poll_app/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
    </body>
</html>

basic_poll_app/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Polls App</title>
    </head>
    <body>
        {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                    <li><a href="{% url 'polls:detail' question.id %}">
                        {{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No polls available...</p>
        {% endif %}
    </body>
</html>